# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'reseacrhapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Mantle'
  pod 'RealmSwift'#, '~> 10.0'
  pod 'SnapKit'

  # Pods for reseacrhapp

  target 'reseacrhappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reseacrhappUITests' do
    # Pods for testing
  end

end
